### Exercicio 1

In [10]:
import numpy as np

arr= np.ones(8)
print(arr)
arr2=np.random.randint(0,9,8)
print(arr2)

soma= arr2 + arr

print(soma)

if soma.sum() >=40:
    soma=soma.reshape(4,2)

else:
    soma=soma.reshape(2,4)

print(soma)


[1. 1. 1. 1. 1. 1. 1. 1.]
[6 4 3 6 3 6 2 5]
[7. 5. 4. 7. 4. 7. 3. 6.]
[[7. 5.]
 [4. 7.]
 [4. 7.]
 [3. 6.]]


### Exercicio 2

In [17]:
arr= np.arange(0,51,2)
arr2=np.arange(100,50,-2)

total= np.concatenate((arr,arr2))
total=np.sort(total)
print(total)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### Exercicio 3

In [23]:
linhas=2
colunas=2

arr=np.zeros((2,2))

arr = np.random.randint(1,1, (linhas, colunas))

print(arr)

ValueError: low >= high

### Exercicio 4

In [28]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

linhas, colunas = arr.shape


num_elementos = linhas * colunas


tipo = "par" if num_elementos % 2 == 0 else "ímpar"


# Exibindo resultados
print("Matriz:\n", arr)
print(f"Número total de elementos: {num_elementos} ({tipo})")


Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Número total de elementos: 9 (ímpar)


### Exercicio 5

In [31]:
np.random.seed(10)

matriz= np.random.randint(0,50,[4,4])

media_linhas = matriz.mean(axis=1)
media_colunas = matriz.mean(axis=0)

print(media_linhas)
print(media_colunas)

maxMedia_linha = np.max(media_linhas)
maxMedia_coluna = np.max(media_colunas)


print("Matriz gerada:\n", matriz)
print("\nMédia de cada linha:", media_linhas)
print("Média de cada coluna:", media_colunas)
print("\nMaior média das linhas:", maxMedia_linha)
print("Maior média das colunas:", maxMedia_coluna)

[15.   32.75 33.5  22.75]
[28.75 23.25 32.75 19.25]
Matriz gerada:
 [[ 9 36 15  0]
 [49 28 25 29]
 [48 29 49  8]
 [ 9  0 42 40]]

Média de cada linha: [15.   32.75 33.5  22.75]
Média de cada coluna: [28.75 23.25 32.75 19.25]

Maior média das linhas: 33.5
Maior média das colunas: 32.75
